DROP TABLE RESERVATION;
DROP TABLE USER;
DROP TABLE GRADE;
DROP TABLE HOTEL;

CREATE TABLE `HOTEL` (
	`HOTEL_NO`	    int	AUTO_INCREMENT PRIMARY KEY NOT NULL	COMMENT '호텔 번호',
	`HOTEL_NAME`	varchar(50)	                   NOT NULL	COMMENT '호텔 이름',
	`HOTEL_GRADE`	int	                           NOT NULL COMMENT '호텔 등급',
	`HOTEL_ADDRESS`	varchar(200)	               NOT NULL	COMMENT '호텔 주소',
	`HOTEL_PHONE`	char(13)	                   NOT NULL	COMMENT '호텔 연락처'
);

CREATE TABLE `RESERVATION` (
	`REV_NO`	int AUTO_INCREMENT NOT NULL PRIMARY KEY               COMMENT '예약 번호',
	`HOTEL_NO`	int	               NOT NULL	                          COMMENT '호텔 번호',
	`USER_NO`	int	               NOT NULL	                          COMMENT '회원 번호',
	`REV_DATE`	datetime	           NULL	DEFAULT current_timestamp COMMENT '예약 날짜',
	`IN_DATE`	datetime	           NULL	DEFAULT current_timestamp COMMENT '체크인 날짜',
	`OUT_DATE`	datetime	           NULL	DEFAULT current_timestamp COMMENT '체크아웃 날짜'
);

CREATE TABLE `USER` (
	`USER_NO`	  int AUTO_INCREMENT NOT NULL PRIMARY KEY               COMMENT '회원 번호',
	`USER_ID`	  varchar(50)	     NOT NULL UNIQUE                    COMMENT '회원 아이디',
	`USER_PWD`	  varchar(50)	     NOT NULL	                        COMMENT '회원 비밀번호',
	`USER_NAME`   varchar(50)	     NOT NULL	                        COMMENT '회원명',
	`USER_PHONE`  char(11)	             NULL	                        COMMENT '회원 연락처',
	`USER_EMAIL`  varchar(100)	         NULL	                        COMMENT '회원 이메일',
	`ENROLL_DATE` datetime	             NULL DEFAULT current_timestamp	COMMENT '회원 가입일',
	`STATUS`	  char(1)	             NULL DEFAULT 'Y'	            COMMENT '상태(Y/N)',
	`GRADE_NO`	  int	                 NULL DEFAULT 1                 COMMENT '회원 등급'
);

CREATE TABLE `GRADE` (
	`GRADE_NO`	  int PRIMARY KEY NOT NULL COMMENT '등급 번호',
	`GRADE_TITLE` varchar(50)	      NULL COMMENT '등급명'
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (HOTEL_NO) REFERENCES HOTEL (HOTEL_NO);
ALTER TABLE RESERVATION ADD FOREIGN KEY (USER_NO)  REFERENCES USER  (USER_NO);
ALTER TABLE USER        ADD FOREIGN KEY (GRADE_NO) REFERENCES GRADE (GRADE_NO);

# SAMPLE DATA
# GRADE
INSERT INTO GRADE VALUES(1, 'SILVER');
INSERT INTO GRADE VALUES(2, 'GOLD');
INSERT INTO GRADE VALUES(3, 'DIAMOND');
INSERT INTO GRADE VALUES(4, 'DIAMOND PLUS');
# USER
INSERT INTO USER (USER_ID, USER_PWD, USER_NAME)VALUES('test01', 'test01', '테스트계정01');
INSERT INTO USER (USER_ID, USER_PWD, USER_NAME)VALUES('test02', 'test02', '테스트계정02');
INSERT INTO USER (USER_ID, USER_PWD, USER_NAME)VALUES('test03', 'test03', '테스트계정03');
#HOTEL
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔1', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔2', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔3', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔4', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔5', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔6', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔7', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔8', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔9', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔10', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔11', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔12', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔13', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔14', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔15', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔16', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔17', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔18', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔19', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔20', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔21', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔22', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔23', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔24', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔25', 3, '서울시 어딘가', '02-1234-5678');
INSERT INTO HOTEL (HOTEL_NAME, HOTEL_GRADE, HOTEL_ADDRESS, HOTEL_PHONE) VALUES('테스트호텔26', 3, '서울시 어딘가', '02-1234-5678');